### ISSUE TITLE
autoboot in cdtv mode

### ISSUE THREAD

**Issue by rzookol** [MHeinrichs/CDTV-RAM-IDE#1]
Hi, maybe i did something wrong but i cannot make autoboot when cdtv mode is activated (with 2.30 bootrom). Tested with oktagon/oktapussy mode and kick 3.1 and kick 3.0.  When booted from cdrom, hd is visible without problems.

**Comment by MHeinrichs** [comment]
Yes this is actually an issue with the CDTV-ROM. It does not load boot code from AutoConfig-devices. Only boot-code in the kickstart itself and the CDTV-ROM is executed before the "CD-Screen". That includes Cd, floppy , the internal SCSI-Controller and any "A600/Gayle-clone" IDE options, if you use kickstart 3.1. This is a strong downer for this expansion. However the HDD-partioins are auto-mounted but not auto boot!

There are three workarounds: 

1st: Make a boot-CD (use google for tutorials it is possible but not simple to make one), which redirects the system shortly after boot to the mounted HDs. Pro: Short boot time and no extra hardware requried. Con: The CDTV reboots after ejecting the CD (because it thinks you removed the original boot media, no one thought of multiple CD-games in 1990!)

2nd: Make a boot floppy, like the CD. Of course you need a floppy drive attached to the CDTV and booting is a bit slower. As far as I remember CDs can be ejected that way without reboot.

3rd: Build your own Kickstart 3.1 and remove the scsi.device (which is actually an ide.device) from it and replace it with the oktagon/oktapussy-device from the boot rom. This is the most complicated sollution and might result in incompatibilities.

**Comment by rzookol** [comment]
Ok, thx, i did 3rd option an it works (took AT file  from oktapussy aminet package).
